### ISSUE TITLE
"No such file .git/config" error

### ISSUE THREAD

**Issue by MartinPavlik** [fregante/setup-git-token#1]
Hi,

I'm having issues running this workflow:
```
name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Initial checkout 
      uses: actions/checkout@master
    - name: Inject token (creates .netrc file)
      uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

It gives me this error:
```
Run fregante/setup-git-token@v1
/home/martin/actions-runner/_work/_actions/fregante/setup-git-token/v1/index.js:11
		throw err;
		^

[Error: ENOENT: no such file or directory, open '.git/config'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.git/config'
}
##[error]Node run failed with exit code 1
```

When I check the working directory, the `.git` directory is missing, any idea what can be wrong?

Thanks :+1: 

## Update
After some debugging I foud out that this is the problem:

```
Deleting the contents of '/home/martin/actions-runner/_work/mtg-db/mtg-db'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```
